spring.application.name=half-life

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/half_life_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:8f4e9a2b7c1d6e3f5a8b0c9d2e4f7a1b3c6d9e2f5a8b1c4d7e0f3a6b9c2d5e8f}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}